poc change for netsuite connector (#5)
* poc change for netsuite connector

diff --git a/.github/workflows/canonical-ci.yml b/.github/workflows/canonical-ci.yml
--- a/.github/workflows/canonical-ci.yml
+++ b/.github/workflows/canonical-ci.yml
@@ -58,3 +58,57 @@ jobs:
           git fetch main ${MAIN_BRANCH_NAME}
           git checkout main/${MAIN_BRANCH_NAME} -- .github
           git checkout main/${MAIN_BRANCH_NAME} -- airbyte-ci
+
+  check_connector_version:
+    name: Check connector version
+    if: github.event.pull_request.head.repo.fork == true
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0 # Ensure the full history is fetched
+      - name: Detect changed connectors
+        id: changes
+        run: |
+          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
+            BASE_COMMIT=$(git rev-parse HEAD~3)
+          elif [ "${{ github.event_name }}" = "push" ]; then
+            BASE_COMMIT=${{ github.event.before }}
+          else
+            BASE_COMMIT=${{ github.event.pull_request.base.sha }}
+          fi
+
+          echo "BASE_COMMIT=$BASE_COMMIT"
+          echo "::set-output name=base_commit::$BASE_COMMIT"
+
+          CHANGED_DIRS=$(git diff --name-only $BASE_COMMIT $GITHUB_SHA | grep '^airbyte-integrations/connectors/' | cut -d/ -f3 | sort -u)
+          echo "Changed connector directories: $CHANGED_DIRS"
+          echo "::set-output name=dirs::$CHANGED_DIRS"
+
+      - name: Check connector version
+        id: version-check
+        run: |
+          BASE_COMMIT=${{ steps.changes.outputs.base_commit }}
+          for DIR in ${{ steps.changes.outputs.dirs }}; do
+            if [ -d "airbyte-integrations/connectors/$DIR" ]; then
+              DOCKERFILE="airbyte-integrations/connectors/$DIR/Dockerfile"
+              echo "DOCKERFILE=$DOCKERFILE"
+              NEW_VERSION=$(grep 'LABEL io.airbyte.version' $DOCKERFILE | cut -d'=' -f2 | tr -d '" ')
+
+              echo "BASE_COMMIT=$BASE_COMMIT"
+              git checkout $BASE_COMMIT
+              BASE_VERSION=$(grep 'LABEL io.airbyte.version' $DOCKERFILE | cut -d'=' -f2 | tr -d '" ')
+
+              # Switch back to the current commit
+              git checkout $GITHUB_SHA
+
+              echo "NEW_VERSION=$NEW_VERSION"
+              echo "BASE_VERSION=$BASE_VERSION"
+              if [ "$NEW_VERSION" == "$BASE_VERSION" ]; then
+                echo "Error: Connector version has not changed in $DOCKERFILE"
+                exit 1
+              fi
+              echo "Connector version has changed for $DIR: $BASE_VERSION -> $NEW_VERSION"
+            fi
+          done
