added matrix

diff --git a/.github/workflows/canonical_ci.yml b/.github/workflows/canonical_ci.yml
--- a/.github/workflows/canonical_ci.yml
+++ b/.github/workflows/canonical_ci.yml
@@ -39,6 +39,7 @@ jobs:
         run: |
           echo "The fork has changes in protected paths. This is not allowed."
           exit 1
+
   check_connector_version:
     name: Check connector version
     if: github.event.pull_request.head.repo.fork == true
@@ -85,11 +86,32 @@ jobs:
             fi
           done
 
+  get-changed-directories-list:
+    name: Get List Of Changed Directories
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout fork with full history
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+          ref: ${{ github.head_ref }}
+          fetch-depth: 0
+      - name: Detect changed connectors
+        id: detect-changes
+        uses: ./.github/actions/detect-changes
+        with:
+          base_commit: ${{ github.event.pull_request.base.sha }}
+          head_commit: ${{ github.event.pull_request.head.sha }}
+
   connectors_full_ci:
     name: Run connectors full CI on fork
     if: github.event.pull_request.head.repo.fork == true
-    needs: fail_on_protected_path_changes
+    needs: [fail_on_protected_path_changes, get-changed-directories-list]
     runs-on: ubuntu-22.04
+    strategy:
+      matrix:
+        dir: ${{ fromJson(needs.get-changed-directories-list.outputs.connectors_list) }}
+
     steps:
       - name: Checkout fork with full history
         uses: actions/checkout@v4
@@ -105,14 +127,7 @@ jobs:
           airbyte_ci_binary_url: ${{ inputs.airbyte_ci_binary_url }}
           is_fork: ${{ inputs.is_fork }}
 
-      - name: Detect changed connectors
-        id: detect-changes
-        uses: ./.github/actions/detect-changes
-        with:
-          base_commit: ${{ github.event.pull_request.base.sha }}
-          head_commit: ${{ github.event.pull_request.head.sha }}
-
-      - name: Test Changed Connectors
+      - name: Test Connector ${{ matrix.dir }}
         id: test-airbyte-ci
         env:
           CI_GIT_BRANCH: ${{ github.head_ref }}
@@ -121,6 +136,11 @@ jobs:
           HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
           HEAD_REF: ${{ github.event.pull_request.head.sha }}
         run: |
+          if [ -z "${{ matrix.dir }}" ]; then
+            echo "No directory specified in matrix.dir, skipping."
+            exit 0
+          fi
+
           # install required packages
           sudo apt update
           sudo apt install python3-setuptools -y
@@ -128,54 +148,54 @@ jobs:
 
           git checkout $CI_GIT_BRANCH
 
-          for CONNECTOR in ${{ steps.detect-changes.outputs.connectors_list }}; do
-            echo "🔄 Running tests for connector: $CONNECTOR"
-            cd airbyte-integrations/connectors/$CONNECTOR
+          CONNECTOR = ${{ matrix.dir }}
 
-            # Run tests for the connector. Skip the tests which are relevant to upstream repository.
-            airbyte-ci --disable-update-check --disable-dagger-run connectors --name=$CONNECTOR test \
-                --skip-step=qa_checks --skip-step=version_inc_check --skip-step=acceptance --skip-step=python_cli_validation
+          echo "🔄 Running tests for connector: $CONNECTOR"
+          cd airbyte-integrations/connectors/$CONNECTOR
 
-            cd ../../../
-            # Find the latest timestamped report directory inside the CI branch folder
-            REPORT_DIR=$(find airbyte-ci/connectors/pipelines/pipeline_reports/airbyte-ci/connectors/test/manual/"$CI_GIT_BRANCH" -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1)
-            echo "Report dir is $REPORT_DIR"
+          # Run tests for the connector. Skip the tests which are relevant to upstream repository.
+          airbyte-ci --disable-update-check --disable-dagger-run connectors --name=$CONNECTOR test \
+              --skip-step=qa_checks --skip-step=version_inc_check --skip-step=acceptance --skip-step=python_cli_validation
 
-            if [[ -z "$REPORT_DIR" ]]; then
-                echo "❌ Error: No report directory found for branch $CI_GIT_BRANCH."
-                exit 1
-            fi
+          cd ../../../
+          # Find the latest timestamped report directory inside the CI branch folder
+          REPORT_DIR=$(find airbyte-ci/connectors/pipelines/pipeline_reports/airbyte-ci/connectors/test/manual/"$CI_GIT_BRANCH" -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1)
+          echo "Report dir is $REPORT_DIR"
 
-            # Find the latest commit hash directory inside the timestamped directory
-            COMMIT_DIR=$(find "$REPORT_DIR" -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1)
+          if [[ -z "$REPORT_DIR" ]]; then
+              echo "❌ Error: No report directory found for branch $CI_GIT_BRANCH."
+              exit 1
+          fi
 
-            if [[ -z "$COMMIT_DIR" ]]; then
-                echo "❌ Error: No commit directory found inside $REPORT_DIR."
-                exit 1
-            fi
-            echo "Commit dir is $COMMIT_DIR"
+          # Find the latest commit hash directory inside the timestamped directory
+          COMMIT_DIR=$(find "$REPORT_DIR" -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1)
 
-            # Extract connector name dynamically from the JSON file if available
-            OUTPUT_JSON=$(find "$COMMIT_DIR" -mindepth 3 -maxdepth 3 -type f -name "output.json" | head -n 1)
+          if [[ -z "$COMMIT_DIR" ]]; then
+              echo "❌ Error: No commit directory found inside $REPORT_DIR."
+              exit 1
+          fi
+          echo "Commit dir is $COMMIT_DIR"
 
-            if [[ ! -f "$OUTPUT_JSON" ]]; then
-                echo "⚠️ Warning: Test report JSON not found in $COMMIT_DIR, failing build to be safe."
-                ls $COMMIT_DIR
-                exit 1
-            fi
+          # Extract connector name dynamically from the JSON file if available
+          OUTPUT_JSON=$(find "$COMMIT_DIR" -mindepth 3 -maxdepth 3 -type f -name "output.json" | head -n 1)
 
-            # Extracting the connector name dynamically
-            CONNECTOR_NAME=$(jq -r '.connector_technical_name' "$OUTPUT_JSON")
+          if [[ ! -f "$OUTPUT_JSON" ]]; then
+              echo "⚠️ Warning: Test report JSON not found in $COMMIT_DIR, failing build to be safe."
+              ls $COMMIT_DIR
+              exit 1
+          fi
 
-            # Extract the success field and failed steps
-            SUCCESS=$(jq -r '.success' "$OUTPUT_JSON")
-            FAILED_STEPS=$(jq -r '.failed_steps[]' "$OUTPUT_JSON")
+          # Extracting the connector name dynamically
+          CONNECTOR_NAME=$(jq -r '.connector_technical_name' "$OUTPUT_JSON")
 
-            if [[ "$SUCCESS" == "false" ]]; then
-                echo "❌ Connector tests failed for $CONNECTOR_NAME."
-                echo "🚨 Failed steps: $FAILED_STEPS"
-                exit 1
-            else
-                echo "✅ All connector tests passed for $CONNECTOR_NAME!"
-            fi
-          done
+          # Extract the success field and failed steps
+          SUCCESS=$(jq -r '.success' "$OUTPUT_JSON")
+          FAILED_STEPS=$(jq -r '.failed_steps[]' "$OUTPUT_JSON")
+
+          if [[ "$SUCCESS" == "false" ]]; then
+              echo "❌ Connector tests failed for $CONNECTOR_NAME."
+              echo "🚨 Failed steps: $FAILED_STEPS"
+              exit 1
+          else
+              echo "✅ All connector tests passed for $CONNECTOR_NAME!"
+          fi
