refactoring for ci/Cd pipelines

diff --git a/.github/workflows/canonical_cd.yml b/.github/workflows/canonical_cd.yml
--- a/.github/workflows/canonical_cd.yml
+++ b/.github/workflows/canonical_cd.yml
@@ -6,9 +6,30 @@ on:
       - master
 
 jobs:
+  get-changed-directories-list:
+    name: Get List Of Changed Directories
+    runs-on: ubuntu-22.04
+    outputs:
+      connectors_list_json: ${{ steps.detect-changes.outputs.connectors_list_json }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0 # Ensure full history
+      - name: Detect changed connectors
+        id: detect-changes
+        uses: ./.github/actions/detect-changes
+        with:
+          base_commit: ${{ github.event.before }}
+          head_commit: ${{ github.sha }}
+
   build-and-push:
     runs-on: ubuntu-22.04
-
+    if: needs.detect-changes.outputs.connectors_list_json != '[]'
+    needs: [get-changed-directories-list]
+    strategy:
+      matrix:
+        dir: ${{ fromJson(needs.get-changed-directories-list.outputs.connectors_list_json) }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -32,21 +53,15 @@ jobs:
           airbyte_ci_binary_url: ${{ inputs.airbyte_ci_binary_url }}
           is_fork: ${{ inputs.is_fork }}
 
-      - name: Detect changed connectors
-        id: detect-changes
-        uses: ./.github/actions/detect-changes
-        with:
-          base_commit: ${{ github.event.before }}
-          head_commit: ${{ github.sha }}
-
-      - name: Build and push Docker images
+      - name: Build and push Docker images for connector ${{ matrix.dir }}
         id: build-and-push-images
         env:
           CI_GIT_BRANCH: ${{ github.head_ref }}
+          CONNECTOR: ${{ matrix.dir }}
         run: |
-          if [[ -z "${{ steps.detect-changes.outputs.connectors_list }}" ]]; then
-            echo "No changed connectors to build. Exiting."
-            exit 0
+          if [ ! -d "airbyte-integrations/connectors/$CONNECTOR" ]; then
+              echo "⚠️ Warning: Connector directory airbyte-integrations/connectors/$CONNECTOR not found! Skipping..."
+              exit 0
           fi
 
           # install required packages
@@ -54,49 +69,39 @@ jobs:
           sudo apt install python3-setuptools -y
           pip install --upgrade setuptools
 
-          for CONNECTOR in ${{ steps.detect-changes.outputs.connectors_list }}; do
-            if [ ! -d "airbyte-integrations/connectors/$CONNECTOR" ]; then
-                echo "⚠️ Warning: Connector directory airbyte-integrations/connectors/$CONNECTOR not found! Skipping..."
-                continue
-            fi
-            
-            METADATAFILE="airbyte-integrations/connectors/$CONNECTOR/metadata.yaml"
+          METADATAFILE="airbyte-integrations/connectors/$CONNECTOR/metadata.yaml"
 
-            # Extract metadata
-            VERSION=$(grep 'canonicalImageTag' $METADATAFILE | cut -d':' -f2 | tr -d '" ')
-            NAME=$(grep 'dockerRepository' $METADATAFILE | cut -d':' -f2 | tr -d '" ')
-            IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/$NAME:$VERSION"
+          # Extract metadata
+          VERSION=$(grep 'canonicalImageTag' $METADATAFILE | cut -d':' -f2 | tr -d '" ')
+          NAME=$(grep 'dockerRepository' $METADATAFILE | cut -d':' -f2 | tr -d '" ')
+          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/$NAME:$VERSION"
 
-            echo "🚀 Building $CONNECTOR with airbyte-ci..."
-            
-            # If build_customization.py already exists, exit with an error
-            if [[ -f build_customization.py ]]; then
-              echo "❌ Error: build_customization.py already exists in $CONNECTOR! Please edit it and add proxy configuration."
-              exit 1
-            fi
-            
-            .github/scripts/generate_build_customizations.sh $CONNECTOR
+          echo "🚀 Building $CONNECTOR with airbyte-ci..."
 
-            cd airbyte-integrations/connectors/$CONNECTOR
+          # If build_customization.py already exists, exit with an error
+          if [[ -f build_customization.py ]]; then
+            echo "❌ Error: build_customization.py already exists in $CONNECTOR! Please edit it and add proxy configuration."
+            exit 1
+          fi
 
-            # Set proxy environment variables
-            export IMAGE_HTTP_PROXY=${{ vars.HTTP_PROXY }}
-            export IMAGE_HTTPS_PROXY=${{ vars.HTTPS_PROXY }}
+          .github/scripts/generate_build_customizations.sh $CONNECTOR
 
-            # Build image using airbyte-ci
-            airbyte-ci connectors --name=$CONNECTOR build
-            
-            # Ensure the dev-tagged image exists before pushing
-            DEV_IMAGE="airbyte/$CONNECTOR:dev"
-            if docker images --format "{{.Repository}}:{{.Tag}}" | grep -q "$DEV_IMAGE"; then
-              echo "✅ Found built image: $DEV_IMAGE"
-              docker tag "$DEV_IMAGE" "$IMAGE_NAME"
-              docker push "$IMAGE_NAME"
-            else
-              echo "❌ Error: Image $DEV_IMAGE was not found after build."
-              exit 1
-            fi
+          cd airbyte-integrations/connectors/$CONNECTOR
 
-            cd ../../../
+          # Set proxy environment variables
+          export IMAGE_HTTP_PROXY=${{ vars.HTTP_PROXY }}
+          export IMAGE_HTTPS_PROXY=${{ vars.HTTPS_PROXY }}
 
-          done
+          # Build image using airbyte-ci
+          airbyte-ci connectors --name=$CONNECTOR build
+
+          # Ensure the dev-tagged image exists before pushing
+          DEV_IMAGE="airbyte/$CONNECTOR:dev"
+          if docker images --format "{{.Repository}}:{{.Tag}}" | grep -q "$DEV_IMAGE"; then
+            echo "✅ Found built image: $DEV_IMAGE"
+            docker tag "$DEV_IMAGE" "$IMAGE_NAME"
+            docker push "$IMAGE_NAME"
+          else
+            echo "❌ Error: Image $DEV_IMAGE was not found after build."
+            exit 1
+          fi
